name: GitHub Actions Demo
on: [push]
jobs:
  Test-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: build Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
      - name: run Docker image
        run: docker run ${{ github.repository }}:latest
